version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-spam-filter-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
